name: Build and Test Predastore

on:
  push:
    branches: ["main"]
    paths: ["predastore/**", ".github/workflows/**"]

jobs:
  hive_test_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Check go.mod for required version
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: Run Tests
        run: LOG_IGNORE=1 go test -v ./...

      - name: golang-govulncheck-action
        uses: golang/govulncheck-action@v1.0.4
        with:
          repo-checkout: false
